stages:
  - test
  - deploy

image: python:latest

before_script:
  - pip install -r requirements.txt
  - pip install pytest

smoke test:
  stage: test
  script:
    - python main.py &
    - sleep 20
    - curl http://localhost:5000/api/health | grep "UP"

unit test:
  stage: test
  script:
    - python -m unittest tests/test_get_highest_id_car.py
    - python -m pytest --junitxml=report.xml
  artifacts:
    when: always
    reports:
      junit: report.xml