stages:
  - test
  - deploy
  - postman test

image: python:latest

.requirements:
  script:
    - pip install -r requirements.txt
    - pip install pytest

.smoke test:
  extends: .requirements
  stage: test
  script:
    - python main.py &
    - sleep 20
    - curl http://localhost:5000/api/health | grep "UP"

.unit test:
  extends: .requirements
  stage: test
  script:
    - python -m unittest tests/test_get_highest_id_car.py
    - python -m pytest --junitxml=report.xml
  artifacts:
    when: always
    reports:
      junit: report.xml

test api:
  stage: postman test
  image:
    name : vdespa/newman
    entrypoint: [""]
  script:
    - newman --version
    - newman run "data/My Cars API.postman_collection.json" --environment data/Localhost.postman_environment.json --reporters cli, htmlextra, junit --reporter-htmlextra-export "newman/report.html" --reporter-junit-export "newman/report.xml"
  artifacts:
    when: always
    paths:
      - newman/
    reports:
      junit: newman/report.xml