stages:
  - build
  - test
  - deploy

image: python:latest

before_script:
  - pip install -r requirements.txt

run_api:
  stage: build
  script:
    - python main.py &
    - sleep 20
    - curl http://localhost:5000/api/health | grep "UP"