stages:
  - build
  - test
  - deploy

image: python:latest

before_script:
  - pip install -r requirements.txt

run_api:
  stage: build
  script:
    - python main.py
    - echo "Welcome to my API Flask"